### ISSUE TITLE
Updating Resource Definitions After Scaffolding

### ISSUE THREAD

**Issue by kleijnweb** [kleijnweb/swagger-bundle#3]
Approximate README addition when finished:

This command can also amend your document to reflect changes in your resource classes. This requires a little configuration:

```yml
swagger.dev.fixer.swagger_bundle_response:
    class: KleijnWeb\SwaggerBundle\Dev\DocumentFixer\Fixers\SwaggerBundleResponseFixer
    calls: [chain, [@swagger.dev.fixer.resource_definitions]]
```
The `ResourceDefinitionFixer` depends on valid `@return` PHPDoc tags (it'll handle arrays of objects, eg `Pet[]`).
