### ISSUE TITLE
Generate Symfony Security/Firewall config

### ISSUE THREAD

**Issue by cirnatdan** [kleijnweb/swagger-bundle#95]
Currently the `security` and `securityDefinition` OpenAPI objects are not supported.
Example:
```
security:
    - api_key: []
securityDefinitions:
    api_key:
        type: apiKey
        name: api_key
        in: header
```
